# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "140b69672ecd7df85b5c1b06e7940e8af75099145623ab0632c9e4e3e0782c43"
      url "https://github.com/cognisivelabs/recall-cli/releases/download/v#{version}/recall_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e3575054d4a4612139914c43e8288f149a925e7d61c882c37dcfed98a223f13"
      url "https://github.com/cognisivelabs/recall-cli/releases/download/v#{version}/recall_darwin_arm64.tar.gz"
    end
  end

  name "recall"
  desc "Your external memory for the terminal. Save, search, and execute commands."
  homepage "https://github.com/cognisivelabs/recall-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recall"

  # No zap stanza required

end
