# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "cf4e4a65a9ff2ed33372e3cb1bd9374df7d96da9883840c099cfa0961854d789"
      url "https://github.com/cognisivelabs/recall-cli/releases/download/v#{version}/recall_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "18d7a0f881e3e3f9ef8d52f31256a5f203553e2ba026d723d0a169c33aace20b"
      url "https://github.com/cognisivelabs/recall-cli/releases/download/v#{version}/recall_darwin_arm64.tar.gz"
    end
  end

  name "recall"
  desc "Your external memory for the terminal. Save, search, and execute commands."
  homepage "https://github.com/cognisivelabs/recall-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recall"

  # No zap stanza required

end
